# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np
print("NumPy Version Installed: ", np.__version__)

NumPy Version Installed:  1.25.2


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
li = [67,89,90,45,76,89]
print(li)
np_ar1 = np.array(li)
print(np_ar1)

[67, 89, 90, 45, 76, 89]
[67 89 90 45 76 89]


In [5]:
# Checking for the type

print(type(np_ar1))

<class 'numpy.ndarray'>


In [6]:
# Checking for the dimension
print(np_ar1.ndim)

1


In [7]:
# Checking for datatype

print(np_ar1.dtype)

int32


In [19]:
# Checking for the shape
print(np_ar1.shape)

(6,)


In [14]:
# Checking for size of the array

print("Number of Items in a numpy array: ", np_ar1.size)

Number of Items in a numpy array:  6


In [10]:
# Checking for the Space occupied by an individual item
print(np_ar1.itemsize, "Bytes")

4 Bytes


In [11]:
# Checking for the Space occupied by array
print(np_ar1.itemsize*np_ar1.size, "Bytes")

24 Bytes


In [15]:
# Checking for the Space occupied by array
# Alternate solution

np_ar1.nbytes

24

In [18]:
# Changing datatype

li = [67,89,90,45,76,89]
np_ar1 = np.array(li, dtype="int8")
print(np_ar1)
print(np_ar1.itemsize)
print(np_ar1.nbytes)

[67 89 90 45 76 89]
1
6


## Creating a Matrix(2-D Array)

In [16]:
np_ar2 = np.array([[45,87,98],
                  [65,38,89],
                  [104,56,44]])

print(np_ar2)
print(type(np_ar2))
print("Dimension: ", np_ar2.ndim)

[[ 45  87  98]
 [ 65  38  89]
 [104  56  44]]
<class 'numpy.ndarray'>
Dimension:  2


In [20]:
# Checking for the shape
print(np_ar2.shape)

(3, 3)


## Creating a 3-D Array

In [24]:
np_ar3 = np.array([[[1,2,3],
                    [4,5,6],
                   [7,8,9],
                    [10,11,12]],
                  [[13,14,15],
                  [16,17,18],
                  [19,20,21],
                  [22,23,24]]])

print(np_ar3)
print(type(np_ar3))
print(np_ar3.ndim)
print(np_ar3.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
<class 'numpy.ndarray'>
3
(2, 4, 3)


## Creating a 4-D Array

In [2]:
np_ar4d = np.array([[[[56,78,90]]]])
print(np_ar4d)
print(np_ar4d.ndim)
print(np_ar4d.shape)

[[[[56 78 90]]]]
4
(1, 1, 1, 3)


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [3]:
np_array1 = np.arange(10)
print(np_array1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np_array1 = np.arange(1,16)
print(np_array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### zeros and ones

Generate arrays of zeros or ones

In [6]:
np_array2 = np.zeros(5)
np_array2

array([0., 0., 0., 0., 0.])

In [7]:
np_array2 = np.zeros((5,3))
np_array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np_array2.dtype

dtype('float64')

In [9]:
np_array2 = np.zeros((5,3),dtype='int8')
np_array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
np_array2.dtype

dtype('int8')

In [11]:
np_array2 = np.zeros((2,5,3),dtype='int8')
np_array2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [12]:
np_array2 = np.zeros((2,2,5,3),dtype='int8')
np_array2

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]], dtype=int8)

In [ ]:
# Using np.ones()

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np_array3 = np.linspace(1,10,100)
np_array3

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

## eye

Creates an identity matrix

In [16]:
np_array4 = np.eye(2,5)
np_array4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [17]:
np_array4 = np.eye(5,5)
np_array4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# Creating an identity matrix using identity() method

np_array4 = np.identity(5)
np_array4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [28]:
np_array5 = np.random.rand(2,2)
np_array5

array([[0.01777268, 0.71526066],
       [0.27448227, 0.8042627 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [29]:
np_array5 = np.random.randn(2,2)
np_array5

array([[-0.19970889,  1.52652506],
       [ 1.43249424, -0.09841987]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [32]:
np_array6 = np.random.randint(1,100,(3,5))
np_array6

array([[58,  8, 51, 12, 55],
       [30, 37, 89, 68, 77],
       [ 8,  9, 11, 62, 84]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
# dtype, ndim, size, itemsize, shape, nbytes

In [ ]:
# (2,4,5,6) Array: 500-1000, floating number datatype

## Reshape
Returns an array containing the same data with a new shape.

In [33]:
# (2,4,5,6)

np_array7 = np.arange(1,241).reshape((2,4,5,6))
np_array7

array([[[[  1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36],
         [ 37,  38,  39,  40,  41,  42],
         [ 43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66],
         [ 67,  68,  69,  70,  71,  72],
         [ 73,  74,  75,  76,  77,  78],
         [ 79,  80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96],
         [ 97,  98,  99, 100, 101, 102],
         [103, 104, 105, 106, 107, 108],
         [109, 110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119, 120]]],


       [[[121, 122, 123, 124, 125, 126],
         [127, 128, 129, 130, 131, 132],
         [133, 134, 135, 136, 137, 138],
         [139, 140, 141, 142, 143, 144],
      

In [34]:
# (4,3,4,5,3)

np_array8 = np.arange(1,721).reshape((4,3,4,5,3))
np_array8

array([[[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9],
          [ 10,  11,  12],
          [ 13,  14,  15]],

         [[ 16,  17,  18],
          [ 19,  20,  21],
          [ 22,  23,  24],
          [ 25,  26,  27],
          [ 28,  29,  30]],

         [[ 31,  32,  33],
          [ 34,  35,  36],
          [ 37,  38,  39],
          [ 40,  41,  42],
          [ 43,  44,  45]],

         [[ 46,  47,  48],
          [ 49,  50,  51],
          [ 52,  53,  54],
          [ 55,  56,  57],
          [ 58,  59,  60]]],


        [[[ 61,  62,  63],
          [ 64,  65,  66],
          [ 67,  68,  69],
          [ 70,  71,  72],
          [ 73,  74,  75]],

         [[ 76,  77,  78],
          [ 79,  80,  81],
          [ 82,  83,  84],
          [ 85,  86,  87],
          [ 88,  89,  90]],

         [[ 91,  92,  93],
          [ 94,  95,  96],
          [ 97,  98,  99],
          [100, 101, 102],
          [103, 104, 105]],

         [[106, 107, 108],
          [1

In [35]:
np_array8 = np.arange(1,721).reshape((4,3,4,5,-1))
np_array8

array([[[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9],
          [ 10,  11,  12],
          [ 13,  14,  15]],

         [[ 16,  17,  18],
          [ 19,  20,  21],
          [ 22,  23,  24],
          [ 25,  26,  27],
          [ 28,  29,  30]],

         [[ 31,  32,  33],
          [ 34,  35,  36],
          [ 37,  38,  39],
          [ 40,  41,  42],
          [ 43,  44,  45]],

         [[ 46,  47,  48],
          [ 49,  50,  51],
          [ 52,  53,  54],
          [ 55,  56,  57],
          [ 58,  59,  60]]],


        [[[ 61,  62,  63],
          [ 64,  65,  66],
          [ 67,  68,  69],
          [ 70,  71,  72],
          [ 73,  74,  75]],

         [[ 76,  77,  78],
          [ 79,  80,  81],
          [ 82,  83,  84],
          [ 85,  86,  87],
          [ 88,  89,  90]],

         [[ 91,  92,  93],
          [ 94,  95,  96],
          [ 97,  98,  99],
          [100, 101, 102],
          [103, 104, 105]],

         [[106, 107, 108],
          [1

In [36]:
np_array8 = np.arange(1,721).reshape((4,3,4,-1,-1))
np_array8

ValueError: can only specify one unknown dimension

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [37]:
myArray = np.array([45,67,89,45])
print(myArray)

[45 67 89 45]


In [38]:
Maximum = myArray.max()
print(Maximum)

89


In [39]:
Minimum = myArray.min()
print(Minimum)

45


In [40]:
Maximum_ind = myArray.argmax()
Maximum_ind

2

In [42]:
Minimum_ind = myArray.argmin()
Minimum_ind

0

In [43]:
# Create a 2-D array and use max,min,argmax,argmin methods

myArray = np.array([[45,67,89,45],
                    [67,56,123,54],
                   [112,3,5,7]])
print(myArray)

[[ 45  67  89  45]
 [ 67  56 123  54]
 [112   3   5   7]]


In [44]:
Max = myArray.max()
print("Maximum",Max)

Min = myArray.min()
print("Minimum",Min)

Maximum 123
Minimum 3


## Shape

Shape is an attribute that arrays have (not a method):

In [50]:
# Vector

rows = myArray.shape[0]
columns = myArray.shape[1]
print(rows)
print(columns)

3
4


### dtype

You can also grab the data type of the object in the array:

In [51]:
myArray.dtype

dtype('int32')

In [52]:
myArray.dtype=float
myArray

array([[1.42173718e-312, 9.54898106e-313],
       [1.18831764e-312, 1.14587773e-312],
       [6.36598743e-314, 1.48539705e-313]])

In [58]:
myArray.dtype = ('float32')
myArray

array([[6.31e-44, 9.39e-44, 1.25e-43, 6.31e-44],
       [9.39e-44, 7.85e-44, 1.72e-43, 7.57e-44],
       [1.57e-43, 4.20e-45, 7.01e-45, 9.81e-45]], dtype=float32)

In [55]:
type(myArray.dtype)

numpy.dtype[float64]

In [59]:
myArray = np.array([[45,67,89,45],
                    [67,56,123,54],
                   [112,3,5,7]], dtype=float)
print(myArray)

[[ 45.  67.  89.  45.]
 [ 67.  56. 123.  54.]
 [112.   3.   5.   7.]]
