# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [30]:
#Creating sample array
# (15,)
# 500 to 1000

np.random.seed(295)
myArray = np.random.randint(500,1000,(15))


In [31]:
#Show
myArray

array([724, 755, 871, 598, 659, 792, 616, 668, 547, 563, 596, 971, 678,
       675, 944])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [32]:
#Get a value at an index

myArray[4]

659

In [33]:
#Get values in a range

myArray[1:5]

array([755, 871, 598, 659])

In [34]:
#Get values in a range
myArray[:5]

array([724, 755, 871, 598, 659])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [35]:
#Setting a value with index range (Broadcasting)
myArray[:5] = 100

#Show
myArray

array([100, 100, 100, 100, 100, 792, 616, 668, 547, 563, 596, 971, 678,
       675, 944])

In [36]:
# Reset array, we'll see why I had to reset in  a moment
np.random.seed(295)
myArray = np.random.randint(500,1000,(15))

#Show
myArray

array([724, 755, 871, 598, 659, 792, 616, 668, 547, 563, 596, 971, 678,
       675, 944])

In [37]:
#Important notes on Slices
# myArray1 = First 2 items
# myArray2 = Last 2 items
# myArray3 = 1 Middle item only

myArray1 = myArray[:2]
myArray2 = myArray[-2:]
myArray3 = myArray[len(myArray)//2]

#Show slice
print(myArray1)
print(myArray2)
print(myArray3)

[724 755]
[675 944]
668


In [38]:
#Change Slice
myArray = np.arange(1,11)
myArray[:] = 7
#Show Slice again
myArray

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [39]:
#Change Slice
myArray = np.arange(1,11)
myArray[:5] = [10,11,12,13,14]
#Show Slice again
myArray

array([10, 11, 12, 13, 14,  6,  7,  8,  9, 10])

Now note the changes also occur in our original array!

In [40]:
myArray

array([10, 11, 12, 13, 14,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [41]:
#To get a copy, need to be explicit

myArray11 = myArray.copy()
myArray11

array([10, 11, 12, 13, 14,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [42]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Syntax arr_2d[row][column] or arr_2d[row,column]

In [44]:
# Extract 25

arr_2d[1][1]

25

In [45]:
arr_2d[1,1]

25

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Extract 
# [[10 15]
#  [25 30]]

In [48]:
arr_2d[:2,-2:]

array([[10, 15],
       [25, 30]])

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
# Extract
#      [[ 5, 15],
#      [35, 45]]

arr_2d[::2,::2]

array([[ 5, 15],
       [35, 45]])

In [ ]:
# First row & last row
# First column & last column

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [53]:
#Set up matrix
# (6,9)

myArray = np.arange(1,55).reshape((6,9))
myArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [59]:
# Access following array
# [[1 2 7 8]
# [10 11 16 17]
# [37 38 43 44]]

myArray[[0,1,4]]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [63]:
myArray[:,[0,1,6,7]]

array([[ 1,  2,  7,  8],
       [10, 11, 16, 17],
       [19, 20, 25, 26],
       [28, 29, 34, 35],
       [37, 38, 43, 44],
       [46, 47, 52, 53]])

In [64]:
myArray[[0,1,4]][:,[0,1,6,7]]

array([[ 1,  2,  7,  8],
       [10, 11, 16, 17],
       [37, 38, 43, 44]])

Fancy indexing allows the following

In [67]:
myArray[np.ix_([0,1,4],[0,1,6,7])]

array([[ 1,  2,  7,  8],
       [10, 11, 16, 17],
       [37, 38, 43, 44]])

## More Indexing

### Indexing a 3D array

In [9]:
# (3,5,7)

myArray = np.arange(1,106).reshape(3,5,7)
myArray

array([[[  1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19,  20,  21],
        [ 22,  23,  24,  25,  26,  27,  28],
        [ 29,  30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41,  42],
        [ 43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56],
        [ 57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70]],

       [[ 71,  72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91],
        [ 92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105]]])

In [10]:
# Extracting

# [[36 38 40 42]
# [64 66 68 70]]

myArray[1,[0,-1],::2]

array([[36, 38, 40, 42],
       [64, 66, 68, 70]])

In [13]:
# Extracting

# [[71 72 75 76]
# [78 79 82 83],
# [92 93 96 97]]

myArray[np.ix_([2],[0,1,3],[0,1,4,5])]

array([[[71, 72, 75, 76],
        [78, 79, 82, 83],
        [92, 93, 96, 97]]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [71]:
myArray = np.arange(1,11)
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
myArray>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
myArray[myArray>5]

array([ 6,  7,  8,  9, 10])

In [74]:
myArray[myArray<=5]

array([1, 2, 3, 4, 5])