# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [10]:
import numpy as np

myArray = np.arange(0,10)

# show array
myArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Performing addition operation
myArray + myArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Performing subtraction operation
myArray - myArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Warning on division by zero, but not an error!
# Just replaced with nan

myArray / myArray

C:\Users\kk\AppData\Local\Temp\ipykernel_1288\424539615.py:4: RuntimeWarning: invalid value encountered in divide
  myArray / myArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
# Also warning, but not an error instead infinity

1/myArray

C:\Users\kk\AppData\Local\Temp\ipykernel_1288\952171162.py:3: RuntimeWarning: divide by zero encountered in divide
  1/myArray


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
# Performing exponentiation
myArray**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
li = [34,56,78]

for i,j in zip(li,li):
    print(i+j)
    

68
112
156


## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [17]:
#Taking Square Roots
np.sqrt(myArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
#Calcualting exponential (e^)
np.exp(myArray)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
#same as arr.max()
np.max(myArray)    

9

In [20]:
np.sin(myArray)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [21]:
np.log(myArray)

C:\Users\kk\AppData\Local\Temp\ipykernel_1288\1404646676.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(myArray)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Splitting Arrays

In [23]:
myArray = np.arange(1,25).reshape((6,4))
myArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [24]:
# Splitting horizontally
np.hsplit(myArray,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [25]:
# Splitting vertically 

np.vsplit(myArray,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [26]:
# Unpacking of a list

arr1,arr2,arr3 = np.vsplit(myArray,3)
print(arr1)
print(arr2)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]]


## Joining Arrays

In [27]:
# Joining arrays by their rows

combined_rows = np.concatenate([arr1,arr2,arr3])
combined_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [28]:
# Joining arrays by their columns

combined_cols = np.concatenate([arr1,arr2,arr3], axis=1)
combined_cols

array([[ 1,  2,  3,  4,  9, 10, 11, 12, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 13, 14, 15, 16, 21, 22, 23, 24]])